### ISSUE TITLE
Inputs do not occupy the same physical space error

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/ITKPhaseSymmetry#23]
Slicer now switched to ITKv5 so I gave another go of using this filter in Slicer. Build was successful but when I wanted to run the filter it failed with "Inputs do not occupy the same physical space" error.

The test data set is available here: https://1drv.ms/u/s!Arm_AFxB9yqHnM1-c0YPKUFyxx_sJg

Command-line parameters and process output:

<pre>
Found CommandLine Module, target is  C:/D/SlicerHeartExtension-win64dbg/inner-build/lib/Slicer-4.11/cli-modules/Debug/PhaseSymmetryFilter.exe
ModuleType: CommandLineModule
Phase Symmetry Filter command line: 

C:/D/SlicerHeartExtension-win64dbg/inner-build/lib/Slicer-4.11/cli-modules/Debug/PhaseSymmetryFilter.exe --wavelengths 3,3,3,6,6,6,12,12,12 --orientations 1,0,0,0,1,0,0,0,1 --sigma 0.55 --angularBandwidth 3.14 --polarity 0 --noiseThreshold 10 C:/Users/msliv/AppData/Local/Temp/Slicer/DGHEE_vtkMRMLScalarVolumeNodeB.nrrd C:/Users/msliv/AppData/Local/Temp/Slicer/DGHEE_vtkMRMLScalarVolumeNodeC.nrrd 

Inputs do not occupy the same physical space! 
InputImage Spacing: [3.8367384e-01, 3.9261347e-01, 2.5173077e-01], InputImage_1 Spacing: [1.0000000e+00, 1.0000000e+00, 1.0000000e+00]
	Tolerance: 3.8367384e-07
InputImage Direction: -1.0000000e+00 0.0000000e+00 0.0000000e+00
0.0000000e+00 -1.0000000e+00 0.0000000e+00
0.0000000e+00 0.0000000e+00 1.0000000e+00
, InputImage_1 Direction: 1.0000000e+00 0.0000000e+00 0.0000000e+00
0.0000000e+00 1.0000000e+00 0.0000000e+00
0.0000000e+00 0.0000000e+00 1.0000000e+00

	Tolerance: 1.0000000e-06

Phase Symmetry Filter completed with errors
</pre>

Source code (cloned CLI module in the repository and added padding filter as shown in Python example):

https://github.com/SlicerHeart/SlicerHeart/blob/ad7ffff1e6285b7bb0c4296f31c54355ab3d7329/PhaseSymmetryFilter/PhaseSymmetryFilter.cxx

**Comment by thewtex** [comment]
This sounds familiar, was this with *ITKPhaseSymmetry* `master` `HEAD`?

**Comment by lassoan** [comment]
Yes, it is with latest master version.

**Comment by che85** [comment]
Hi there, 
are there any plans of getting these issues fixed? I would like to use the filter for some preprocessing task. Thanks a lot.

**Comment by thewtex** [comment]
@zahilshanis and I are looking into it. Thanks
