### ISSUE TITLE
Padded image is not periodic

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/ITKPhaseSymmetry#24]
I saved output of fftpad in PhaseSymmetryFilter\PhaseSymmetryFilter.cxx and found that the generated image is not periodic. At the boundaries, the image is discontinuous: it seems that the added regions are mirrored compared to the correct .

Example input file: https://1drv.ms/u/s!Arm_AFxB9yqHnM1-c0YPKUFyxx_sJg

Input:

![image](https://user-images.githubusercontent.com/307929/54849940-1320f380-4cbc-11e9-9585-7b5daa5a0524.png)

Output of writer->SetInput(fftpad->GetOutput()):

![image](https://user-images.githubusercontent.com/307929/54850172-c38ef780-4cbc-11e9-8a0a-88da4d938e20.png)

Expected output:

![image](https://user-images.githubusercontent.com/307929/54851031-1d90bc80-4cbf-11e9-8fdc-fba45c3dca66.png)

Source code (cloned CLI module in the repository and added padding filter as shown in Python example):

https://github.com/SlicerHeart/SlicerHeart/blob/ad7ffff1e6285b7bb0c4296f31c54355ab3d7329/PhaseSymmetryFilter/PhaseSymmetryFilter.cxx#L52-L62

**Comment by thewtex** [comment]
There was a flip recently added that I think needs to be reverted. I will investigate.

**Comment by thewtex** [comment]
@zahilshanis

**Comment by thewtex** [comment]
The flip has been removed.

**Comment by lassoan** [comment]
Awesome, thank you!

**Comment by dzenanz** [comment]
Fixed by c59469d652618ca07ef130a5dd488ae19a34e25c.
